# Generated by Django 2.2 on 2021-06-22 21:00

from django.db import migrations
from datetime import date

def load_data(apps, schema_editor):
    PriceHistory = apps.get_model("historical_data", "PriceHistory")

    PriceHistory(date=date(2013,11,29),
         price=123.00,
         volume=354.564,
         ).save()
    PriceHistory(date=date(2012,11,29),
         price=12.15,
         volume=187.947,
         ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, migrations.RunPython.noop)

    ]
