# Generated by Django 2.2 on 2021-06-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0002_switch_to_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='total_btc',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
